permalink:   /:categories/:year/:month/:day/:title
auto:        true
pygments:    true
markdown:    kramdown
include:     [.htaccess]

title : François Klingler
url: http://fklingler.com
author :
  name : François Klingler
  email : contact@fklingler.com
